[tools]
bat = "0.26.1"
bitwarden = "2026.1.0"
dotnet = "10.0.102"
fd = "10.3.0"
fzf = "0.67.0"
gh = "2.86.0"
ghq = "1.8.1"
go = "1.25.7"
jq = "1.8.1"
node = "25.6.0"
"npm:npx" = "10.2.2"
opencode = "1.1.53"
pre-commit = "4.5.1"
terraform = "1.14.4"
terraform-docs = "0.21.0"
tflint = "0.61.0"
trivy = "0.69.1"
