[tools]
bat = "latest"
bitwarden = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
jq = "latest"
opencode = "latest"
pre-commit = "latest"
terraform = "latest"
terraform-docs = "latest"
tflint = "latest"
trivy = "latest"
